### ISSUE TITLE
Plugin will not load

### ISSUE THREAD

**Issue by texxasrulez** [JodliDev/calendar#35]
Since I have not been able to work on my calendar, I went to try yours. The plugin will not load. I am using RC 1.6.1 and PHP8.1. I have the following errors in my log:

[12-Mar-2023 18:33:16 +0000]: PHP Error: Failed to load plugin file /path_to_roundcube/plugins/libkolab/libkolab.php in /path_to_roundcube/program/lib/Roundcube/rcube_plugin_api.php on line 193 (GET /mail/?_task=calendar)
[12-Mar-2023 18:33:16 +0000]: <29fv0ebd> PHP Error: Failed to load plugin file /path_to_roundcube/plugins/libkolab/libkolab.php in /path_to_roundcube/program/lib/Roundcube/rcube_plugin_api.php on line 193 (GET /mail/?_task=calendar)
[12-Mar-2023 18:33:16 UTC] PHP Fatal error:  Uncaught Error: Class "kolab_attachments_handler" not found in /path_to_roundcube/plugins/calendar/lib/calendar_ui.php:107
Stack trace:
#0 /path_to_roundcube/plugins/calendar/calendar.php(326): calendar_ui->init_templates()
#1 /path_to_roundcube/program/lib/Roundcube/rcube_plugin_api.php(575): calendar->calendar_view()
#2 /path_to_roundcube/program/include/rcmail.php(262): rcube_plugin_api->exec_action('calendar.index')
#3 /path_to_roundcube/index.php(278): rcmail->action_handler()
#4 {main}
  thrown in /path_to_roundcube/plugins/calendar/lib/calendar_ui.php on line 107

I do have libkolab from Kolab developers installed as well ... Thank you for your work

**Comment by JodliDev** [comment]
Are you sure that you have installed https://github.com/JodliDev/libcalendaring as well? And uninstalled other calendar variants (and variants of libcalendaring)?
Maybe there are some faulty config files left?

It seems to me that the installations has failed somehow.

**Comment by texxasrulez** [comment]
Yes I have ... I should have been clear when I said I had libkolab from kolab I should have stated I am using your libcalendaring as well

**Comment by JodliDev** [comment]
What version of roundcube are you using?

At the moment I have two theories: Either you are using a very new version of roundcube and they have changed something important or your calendar installation is broken somehow.

**Comment by texxasrulez** [comment]
1.6.1 ... My roundcube is working just fine. I am not some newbie. It appears to have lots of php8 errors. It happens to all of us. You get everything running just great for your plugin and changes come to either RC or PHP and it trows a wrench into the whole thing. Never ending cycle

**Comment by JodliDev** [comment]
Ah my apologies. I didnt see the version mentioned in your initial comment.

I havent tested roundcube 16 yet.
They have finally updated calendar (and libcalendaring) to php 8 but for some reason stopped publishing to the plugin repository (and github). So I am kinda stuck in limbo because I would like to continue using their changes without having to manually copy them over every time - so my love for roundcube has faded a bit^^

**Comment by texxasrulez** [comment]
I wouldn't let these changes fade your love for Roundcube. Not their fault. Main PHP development are the reason for necessary updates. I once liked the challenge of changing ecosystems of the computerverse, but since I am now an official "Old Man", I would just like it to stay the same ... There is my old man joke for the day ... 

Well good luck and keep on trucking my friend ...

**Comment by aryin-github** [comment]
Using roundcube 1.6.5, I tried several calendar plugins however all are stuck with the sabre library. Tried using different version of sabre with no luck. Any comment with this?
I have rcmcarddav 5 installed which work well with its sabre, is there I have missing important step?

most common error,
Class 'Sabre\DAV\Client' not found in plugins/calendar/drivers/caldav/caldav_client.php
tried to add Sabre classes to the code, but finally fail.
