### ISSUE TITLE
Many "Undefined array key" warnings

### ISSUE THREAD

**Issue by michael-markevich** [JodliDev/calendar#52]
I use the current snapshot of the plugin, RC 1.6.5 and PHP 8.2.7. I have received a lot of annoying warnings:

```
PHP Warning:  Undefined array key "port" in /var/www/roundcubemail-1.6.5/plugins/calendar/drivers/caldav/caldav_client.php on line 54
PHP Warning:  Undefined array key "query" in /var/www/roundcubemail-1.6.5/plugins/calendar/drivers/caldav/caldav_client.php on line 55
PHP Warning:  Undefined array key "port" in /var/www/roundcubemail-1.6.5/plugins/calendar/drivers/caldav/caldav_driver.php on line 2068
PHP Warning:  Undefined array key "valarms" in /var/www/roundcubemail-1.6.5/plugins/calendar/drivers/caldav/caldav_driver.php on line 975
PHP Warning:  Undefined array key "valarms" in /var/www/roundcubemail-1.6.5/plugins/calendar/drivers/caldav/caldav_driver.php on line 957
PHP Warning:  Undefined array key "{DAV:}getetag" in /var/www/roundcubemail-1.6.5/plugins/calendar/drivers/caldav/caldav_client.php on line 119
PHP Warning:  Undefined array key "{urn:ietf:params:xml:ns:caldav}calendar-data" in /var/www/roundcubemail-1.6.5/plugins/calendar/drivers/caldav/caldav_client.php on line 163
```

**Comment by SurajDadral** [comment]
Hey @michael-markevich 
Any workaround or fix you found?

I am unable to create event with participants (without participants working), getting error:
```
[17-Jun-2025 11:10:58 UTC] PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /usr/share/roundcube/plugins/calendar/vendor/jodlidev/libcalendaring/libvcalendar.php:1256
Stack trace:
#0 /usr/share/roundcube/plugins/calendar/vendor/jodlidev/libcalendaring/libvcalendar.php(1018): libvcalendar->_to_ical()
#1 /usr/share/roundcube/plugins/calendar/drivers/caldav/caldav_client.php(289): libvcalendar->export()
#2 /usr/share/roundcube/plugins/calendar/drivers/caldav/caldav_sync.php(223): caldav_client->put_event()
#3 /usr/share/roundcube/plugins/calendar/drivers/caldav/caldav_driver.php(535): caldav_sync->create_event()
#4 /usr/share/roundcube/plugins/calendar/calendar.php(1076): caldav_driver->new_event()
#5 /usr/share/roundcube/program/lib/Roundcube/rcube_plugin_api.php(577): calendar->event_action()
#6 /usr/share/roundcube/program/include/rcmail.php(262): rcube_plugin_api->exec_action()
#7 /usr/share/roundcube/index.php(278): rcmail->action_handler()
#8 {main}
  thrown in /usr/share/roundcube/plugins/calendar/vendor/jodlidev/libcalendaring/libvcalendar.php on line 1256
```
